# Generated by Django 4.2.3 on 2024-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct_ans',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
